name: build_and_test

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - humble
      - jazzy
      - '*-devel'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - '*'
  workflow_dispatch:

# Do not run multiple jobs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # build_and_test:
  #   timeout-minutes: 15
  #   strategy:
  #     matrix:
  #       ros_distro: [humble, jazzy, kilted, rolling]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v6
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Docker metadata
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: mujoco_ros2_control
  #         tags: |
  #           type=ref,event=branch
  #           type=ref,event=pr
  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: docker/Dockerfile
  #         tags: ${{ steps.meta.outputs.tags }}
  #         target: mujoco_ros
  #         build-args: |
  #           ROS_DISTRO=${{ matrix.ros_distro }}
  #         push: false
  #         load: true
  #         cache-from: type=gha,scope=ros-${{ matrix.ros_distro }}
  #         cache-to: type=gha,mode=max,scope=ros-${{ matrix.ros_distro }}
  #     - name: Run tests
  #       run: |
  #         docker run --rm \
  #           ${{ steps.meta.outputs.tags }} \
  #           bash -c "
  #             colcon test &&
  #             colcon test-result --verbose
  #           "

  pixi_jazzy_build_and_test:
    timeout-minutes: 15
    env:
      SCCACHE_DIR: ${{ github.workspace }}/.sccache
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      # - name: Cache build directories and sccache
      #   uses: actions/cache@v5
      #   with:
      #     path: |
      #       ${{ env.SCCACHE_DIR }}
      #     key: ${{ runner.os }}-sccache-${{ github.head_ref || github.ref_name }}
      #     restore-keys: |
      #       ${{ runner.os }}-sccache-main
      #       ${{ runner.os }}-sccache-
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: false
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
          manifest-path: pixi.toml
      - name: Build and test
        shell: pixi run bash -e {0}
        run: |
          colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml || true
          colcon mixin update default
          colcon build
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
